### PR TITLE
2569 missing transactions fix

### LINKED ISSUE #2569: Txn not showing in Checking account
From user:

 I’m a new Hexa wallet user. I tried to send some of the bitcoin I had purchased via Coinbase to my Hexa account using the “Bitcoin Receiving Address” generated in my Hexa Checking account. I have a confirmation from Coinbase that the bitcoin was sent, but it still hasn’t recorded in my Hexa account. Can you help?
Data of Transaction: 21 January 2021
Bitcoin Receiving address utilized (*this is the address generated in my Hexa Checking account): 382H5gNVyYpt9aFosGLdjSEVEQVCVivp1r

Bitcoin USD ($) amount: $98.96

Bitcoin amount: 0.00324024

### PR DESCRIPTION
**Pull request by AliMeer**
Fix for missing transactions and utxos for derived sec sub accounts.

Partially fixes #2569 - Fixes the FBTC transaction missing issue.

### CODE REVIEW

File: src/bitcoin/utilities/accounts/HDSegwitWallet.ts [hunk 1]
```diff
@@ -606,9 +606,13 @@ export default class HDSegwitWallet extends Bitcoin {
         this.derivativeAccounts[ dAccountType ][ accountNumber ][
           'usedAddresses'
         ] = usedAddresses // derv used addresses forms a part of ownedAddresses array during primary-acc sync
-        // console.log({ derivativeAccUsedAddresses: usedAddresses });
-
-        const { xpubId } = this.derivativeAccounts[ dAccountType ][ accountNumber ]
+        
+        const xpub = this.generateDerivativeXpub( dAccountType, accountNumber )
```
Comment (Parsh) [inline src/bitcoin/utilities/accounts/HDSegwitWallet.ts:610]: Looks good, only thing is that we don't need to regenerate the xpub(would end up generating a different xpub), xpub can be pulled out of the derivative acccount using the following:
```
const { xpub, xpubId } = this.derivativeAccounts[ dAccountType ][ accountNumber]
if ( !xpubId ) {
          xpubId = crypto.createHash( 'sha256' ).update( xpub ).digest( 'hex' )
          this.derivativeAccounts[ dAccountType ][ accountNumber ].xpubId = xpubId
        }
```

**Review by Parsh — CHANGES_REQUESTED** [review]

File: src/bitcoin/utilities/accounts/HDSegwitWallet.ts (hunk 1 above)
Comment (AliMeer) [reply src/bitcoin/utilities/accounts/HDSegwitWallet.ts]: Kool, updated in new commit.

**Review by Parsh — APPROVED** [review]
